name: Deploy to GitHub Pages

on:
  workflow_dispatch: # Permite que solo se ejecute manualmente desde GitHub Actions.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn deploy
