name: Deploy to GitHub Pages

on:
  # Permite que el flujo se ejecute manualmente desde GitHub Actions.
  workflow_dispatch:

  # Ejecuta automáticamente el despliegue solo cuando se haga push a la rama `master`.
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn deploy
